package org.example.drools.uttt;


rule "盤面に記入したマークデータを削除"
  salience 20
  when
    ResetCmd()
    $mark : Mark()
  then
    delete( $mark );
end

rule "グローバル盤面データを削除"
  salience 20
  when
    ResetCmd()
    $gf : GlobalField()
  then
    delete( $gf );
end

rule "オーバーレイ表示コマンド削除"
  salience 20
  when
    ResetCmd()
    $oc : OverlayCmd()
  then
    delete( $oc );
end

rule "ラベル更新コマンドを削除"
  salience 20
  when
    ResetCmd()
    $labelUpdCmd : LabelUpdCmd()
  then
    delete( $labelUpdCmd );
end

rule "配置コマンドを削除"
  salience 20
  when
    ResetCmd()
    $placeCmd : PlaceCmd()
  then
    delete( $placeCmd );
end

rule "フィールド変更コマンドを削除"
  salience 20
  when
    ResetCmd()
    $fieldChangeCmd : FieldChangeCmd()
  then
    delete( $fieldChangeCmd );
end

rule "ステータス初期化_勝敗確定時"
  salience 10
  when
    $resetCmd : ResetCmd()
    $winner : Winner()
    $gameOverCmd : GameOverCmd()
    $status : GameStatus( isGameOver == true)
  then
    delete( $winner );
    delete( $gameOverCmd );
    delete( $resetCmd );
    modify ( $status ) { isGameOver = false };
end

rule "ステータス初期化_引き分け時"
  salience 10
  when
    $resetCmd : ResetCmd()
    not Winner()
    $gameOverCmd : GameOverCmd()
    $status : GameStatus()
  then
    delete( $gameOverCmd );
    delete( $resetCmd );
    modify ( $status ) { isGameOver = false };
end
