package org.example.drools.ttt;

import org.example.drools.ttt.model.*;
import org.example.drools.ttt.incmd.*;
import org.example.drools.ttt.outcmd.*;


rule "ゲームステータスがなければ作成"
  when
    not GameStatus()
  then
    insert(new GameStatus());
end

rule "◯の手番_マークを生成"
  when
    GameStatus( isGameOver == false )
    $cmd: PlaceCmd(mark == "◯")
    not Mark(row == $cmd.row, col == $cmd.col)
  then
    insert(new Mark($cmd.row(), $cmd.col(), $cmd.mark()));
    insert(new LabelUpdCmd("✕ の番です"));
end

rule "✕の手番_マークを生成"
  when
    GameStatus( isGameOver == false )
    $cmd: PlaceCmd(mark == "✕")
    not Mark(row == $cmd.row, col == $cmd.col)
  then
    insert(new Mark($cmd.row(), $cmd.col(), $cmd.mark()));
    insert(new LabelUpdCmd("◯ の番です"));
end
