package org.example.drools.ttt;

import javax.swing.JLabel;
import org.example.drools.ttt.model.*;
import org.example.drools.ttt.command.*;

rule "プレイヤー"
  when
    not CurrentPlayer()
  then
    insert(new CurrentPlayer("◯"));
end

rule "ゲームステータス"
  when
    not GameStatus()
  then
    insert(new GameStatus());
end

rule "ボタン押下時に手番更新"
  when
    GameStatus( isGameOver == false )
    field : Field( isFilled == false, getBtn().getText() == "" )
    statusLabel: JLabel()
    player: CurrentPlayer()
  then
    field.getBtn().setText(player.getMark());
    modify ( field ) { isFilled = true };
    if (player.getMark() == "◯"){
      player.setMark("✕");
    } else {
      player.setMark("◯");
    }
    statusLabel.setText(player.getMark() + " の番です");
end
